stages:
  preprocess_data:
    cmd: |
      "C:\Program Files\R\R-4.0.4\bin\Rscript" .\src\preprocess_data.R .\params.yaml
    deps:
      - src/preprocess_data.R
      - data/raw/training_set_features.csv
      - data/raw/training_set_labels.csv
    outs:
      - data/processed/train_flushot.csv

  train_model:
    cmd: |
      "C:\Program Files\R\R-4.0.4\bin\Rscript" .\src\train_model.R .\params.yaml
    deps:
      - data/processed/train_flushot.csv
      - src/train_model.R
    outs:
      - models/model_cart.rda
    metrics:
      - reports/scores.json:
          cache: false

  make_submission_file:
    cmd: |
      "C:\Program Files\R\R-4.0.4\bin\Rscript" .\src\make_submission_file.R .\params.yaml
    deps:
      - data/raw/test_set_features.csv
      - src/make_submission_file.R
      - models/model_cart.rda
    outs:
      - reports/submission.csv

