base:
  project: flu_shot_learning
  random_state: 45
  target_col_1: h1n1_vaccine
  target_col_2: seasonal_vaccine
  id_col: respondent_id
  submission_file_path: reports/submission.csv 
  folds: 4

preprocess_data:
  train_path: data/processed/train_flushot.csv
  test_path: data/processed/test_flushot.csv

data:
  raw_data: data/raw/training_set_features.csv
  raw_data_labels: data/raw/training_set_labels.csv
  test_competition: data/raw/test_set_features.csv

model_dir: models
model_path: models/model_cart.rda

scores_path: reports/scores.json
